### ISSUE TITLE
Question : error CS8652 language version mismatch

### ISSUE THREAD

**Issue by PascalSoftwares** [AlTheSlacker/FlaxProcTerrain#2]
I opened the repository with latest Engine editor and it says

> error CS8652: The feature 'primary constructors' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.

I think it is from the source code syntax which requires higher language version in project settings, but I cannot change csproj languave version (11.1) in visual studio, nor in editor options.

 Is this project requires higher .Net version than Flax's requirement(7.0) or something ? Or can I change some settings manually?

**Comment by AlTheSlacker** [comment]
Hi, Sorry, I ended up using net 8 for some other work since it is now out of beta and is officially supported on Flax since 1.7.1. But I thought I rolled the primary constructors out of it to keep it compatible with net 7. I must have missed one. I'll get a fix in within a couple of hours and post here when it is done (sorry busy atm).

**Comment by AlTheSlacker** [comment]
OK that should be fixed now and compliant with net 7 and 8. Please let me know here if everything is OK.
